export const runtime = 'nodejs';
import bcryptjs from 'bcryptjs';
import { countries, Country } from './seed-countries';

// -------------------------
// Interfaces para el seed
// -------------------------

interface SeedCompany {
  name: string;
  email?: string;
  phone?: string;
  logo?: string;
  domains: string[]; // Dominios asociados a la empresa
  categories: string[];
  attributes: SeedAttribute[];
  products: SeedProduct[];
}

interface SeedAttribute {
  name: string;
  type: 'text' | 'number' | 'select' | 'multiselect';
  values?: string[]; // Para select y multiselect
}

interface SeedProduct {
  title: string;
  description: string;
  price: number;
  inStock: number;
  slug: string;
  images: string[];
  category: string;
  tags: string[];
  attributes: Record<string, string | number | string[]>; // nombre del atributo -> valor
}

interface SeedUser {
  email: string;
  password: string;
  name: string;
  role: 'admin' | 'user';
}

interface SeedData {
  companies: SeedCompany[];
  users: SeedUser[];
  countries: Country[];
}

// -------------------------
// Datos de seed
// -------------------------

export const initialData: SeedData = {
  countries: countries,
  users: [
    {
      email: 'admin@misproductos.shop',
      name: 'Admin User',
      password: bcryptjs.hashSync('123456'),
      role: 'admin',
    },
    {
      email: 'test@misproductos.shop',
      name: 'Test User',
      password: bcryptjs.hashSync('123456'),
      role: 'user',
    },
  ],
  companies: [
    {
      name: 'Pastelería Artesanal',
      email: 'pedidos@pasteleria.com',
      phone: '+5491198765432',
      domains: ['pasteleria.misproductos.shop', 'pasteleriaartesanal.com'],
      categories: ['Tortas', 'Postres', 'Panadería', 'Especiales', 'Tartas', 'Cupcakes'],
      attributes: [
        {
          name: 'Sabor',
          type: 'select',
          values: ['Chocolate', 'Vainilla', 'Frutilla', 'Limon', 'Dulce de Leche', 'Maracuyá', 'Frambuesa'],
        },
        {
          name: 'Tamaño',
          type: 'select',
          values: ['Individual', 'Chico (6 porciones)', 'Mediano (12 porciones)', 'Grande (20 porciones)'],
        },
        {
          name: 'Decoración',
          type: 'multiselect',
          values: ['Frutas', 'Chocolate', 'Crema', 'Merengue', 'Sin decoración', 'Fondant'],
        },
        {
          name: 'Peso (kg)',
          type: 'number',
        },
        {
          name: 'Sin TACC',
          type: 'select',
          values: ['Sí', 'No'],
        },
      ],
      products: [
        {
          title: 'Torta de Chocolate Premium',
          description: 'Torta húmeda de chocolate belga con relleno de crema chantilly y cobertura de ganache. Decorada con frutos rojos.',
          price: 45.99,
          inStock: 15,
          slug: 'torta-chocolate-premium',
          images: ['https://imgs.search.brave.com/0yyNfT3MCpCjGLzDicwjoONC-sbA0FnjRBtXrDrT-e0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90YXRh/dXkudnRleGFzc2V0/cy5jb20vdW5zYWZl/LzB4MC9jZW50ZXIv/bWlkZGxlL2h0dHBz/Oi8vdGF0YXV5LnZ0/ZXhhc3NldHMuY29t/L2FycXVpdm9zL2lk/cy8yMjYxNDQvVG9y/dGEtUHJlbWl1bS1U/ZW50YWNpb24tQ2hv/Y29sYXQtU2V2aWxs/YS0xLTAwLVUtMi04/MDc3LmpwZz92PTYz/NzY5MzI1NzkwMDQ3/MDAwMA'],
          category: 'Tortas',
          tags: ['chocolate', 'torta', 'premium', 'postre'],
          attributes: {
            Sabor: 'Chocolate',
            Tamaño: 'Mediano (12 porciones)',
            Decoración: ['Chocolate', 'Crema', 'Frutas'],
            'Peso (kg)': 1.5,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Torta de Frutilla',
          description: 'Torta fresca de frutilla con crema y bizcochuelo de vainilla. Perfecta para cumpleaños.',
          price: 38.99,
          inStock: 12,
          slug: 'torta-frutilla',
          images: ['https://imgs.search.brave.com/76WHHtqEwj1QsCXlEm82-8WhATZBqdN1-pH5qnW6EOM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ub3Rv/bmx5c2FsYWRibG9n/LmNvbS93cC1jb250/ZW50L3VwbG9hZHMv/MjAxOC8xMS9Ub3J0/YV9mcnV0aWxsYXNf/Tk9TYmxvZy01LUxh/cmdlLmpwZw'],
          category: 'Tortas',
          tags: ['frutilla', 'torta', 'fresca', 'cumpleaños'],
          attributes: {
            Sabor: 'Frutilla',
            Tamaño: 'Mediano (12 porciones)',
            Decoración: ['Frutas', 'Crema'],
            'Peso (kg)': 1.3,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Torta Red Velvet',
          description: 'Torta clásica Red Velvet con frosting de queso crema. Elegante y deliciosa.',
          price: 42.99,
          inStock: 10,
          slug: 'torta-red-velvet',
          images: ['https://imgs.search.brave.com/wwk_9VPAj0P3psH1UZ27IpsFb9K0TQUtCdjKAy-iuac/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hY2Ru/LXVzLm1pdGllbmRh/bnViZS5jb20vc3Rv/cmVzLzUyOC82MDgv/cHJvZHVjdHMvYjJm/YjMxYWYtMWJmNi00/OTI5LThhNTAtYjg4/MTQwYzQ4YmE1LWNm/NjZiMmMzZDI2YTli/MWQzODE3NDQxMjI0/NDc1ODY2LTQ4MC0w/LndlYnA'],
          category: 'Tortas',
          tags: ['red velvet', 'torta', 'clásica', 'elegante'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Grande (20 porciones)',
            Decoración: ['Crema', 'Fondant'],
            'Peso (kg)': 2.0,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Alfajores de Maicena',
          description: 'Alfajores caseros rellenos de dulce de leche artesanal, bañados en chocolate semiamargo.',
          price: 2.5,
          inStock: 150,
          slug: 'alfajores-maicena',
          images: ['https://imgs.search.brave.com/64i5oCE6qmR6YSAVdDdfpNUxOzl5htiF78KiA3QUtAc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bGF2b3ouY29tLmFy/L3Jlc2l6ZXIvdjIv/N0FVM0RQNktPSkJV/WkhST0RFNkdRTElI/QVUucG5nP2F1dGg9/MjQ2NWYxMWFmYjU4/MzU2ZjkzZTQxYjky/ZWVjYTk5OTA1ZDBm/YTJiNWZjN2FkNDYz/Yzc2YmQ4NWJjYzli/ZDM2MyZxdWFsaXR5/PTc1JnNtYXJ0PXRy/dWUmd2lkdGg9Mzg1'],
          category: 'Postres',
          tags: ['alfajor', 'dulce de leche', 'tradicional', 'artesanal'],
          attributes: {
            Sabor: 'Dulce de Leche',
            Tamaño: 'Individual',
            Decoración: ['Chocolate'],
            'Peso (kg)': 0.05,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Alfajores Sin TACC',
          description: 'Alfajores sin gluten, rellenos de dulce de leche y bañados en chocolate.',
          price: 3.5,
          inStock: 80,
          slug: 'alfajores-sin-tacc',
          images: ['https://imgs.search.brave.com/8HuLwCqr1_AHMHvR0Sj9Rpy7e52I0Jvb3wijUR3xwWo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hY2Ru/LXVzLm1pdGllbmRh/bnViZS5jb20vc3Rv/cmVzLzAwMS8zOTAv/NTU0L3Byb2R1Y3Rz/LzIxNDEtN2M3MDlh/NzY2NmEwZGIzZDk0/MTYwMzU5MDAwMjA5/OTctMjQwLTAud2Vi/cA'],
          category: 'Postres',
          tags: ['alfajor', 'sin tacc', 'sin gluten', 'especial'],
          attributes: {
            Sabor: 'Dulce de Leche',
            Tamaño: 'Individual',
            Decoración: ['Chocolate'],
            'Peso (kg)': 0.05,
            'Sin TACC': 'Sí',
          },
        },
        {
          title: 'Tarta de Manzana',
          description: 'Tarta casera de manzana con masa quebrada y canela. Caliente o fría, siempre deliciosa.',
          price: 18.99,
          inStock: 25,
          slug: 'tarta-manzana',
          images: ['https://imgs.search.brave.com/qYZEyS1Yk6YKVecVBzvV_32xYy8qztrMke6PLV2e5ME/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWct/Z2xvYmFsLmNwY2Ru/LmNvbS9yZWNpcGVz/L2MzZDA2ZmE1ZWJm/OGYyZDgvMzAweDIy/MGNxODAvdGFydGEt/ZGUtbWFuemFuYS1l/bi1lc3R1ZmEtZm90/by1wcmluY2lwYWwu/anBn'],
          category: 'Tartas',
          tags: ['tarta', 'manzana', 'casera', 'canela'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Chico (6 porciones)',
            Decoración: ['Sin decoración'],
            'Peso (kg)': 0.8,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Tarta de Limón',
          description: 'Tarta refrescante de limón con merengue italiano. Perfecta para el verano.',
          price: 22.99,
          inStock: 20,
          slug: 'tarta-limon',
          images: ['https://imgs.search.brave.com/YB5dJCSZ5lWD-czklUgpCKYczE_XarcIwIi9sWHAfrc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kdWxj/ZXNkaWFiZXRpY29z/LmNvbS93cC1jb250/ZW50L3VwbG9hZHMv/MjAxNi8xMi9UYXJ0/YS1kZS1saW1vbi1z/aW4tYXp1Y2FyLW5p/LWhvcm5vLXdfb3B0/LmpwZw'],
          category: 'Tartas',
          tags: ['tarta', 'limón', 'merengue', 'refrescante'],
          attributes: {
            Sabor: 'Limon',
            Tamaño: 'Chico (6 porciones)',
            Decoración: ['Merengue'],
            'Peso (kg)': 0.9,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Cupcakes de Chocolate',
          description: 'Set de 6 cupcakes de chocolate con frosting de crema de mantequilla. Decorados con sprinkles.',
          price: 15.99,
          inStock: 30,
          slug: 'cupcakes-chocolate',
          images: ['https://imgs.search.brave.com/jJ6g8Gz3nCvDP_1Bol1uByDw4awwtdaoDiFoRVRKOSI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9jaG9j/b2xhdGUtY3VwY2Fr/ZXMtZnJvc3Rpbmct/YmxhY2std2hpdGUt/cG9sa2EtZG90LW91/dHRpbmctNzI1NDkz/NzQuanBn'],
          category: 'Cupcakes',
          tags: ['cupcakes', 'chocolate', 'frosting', 'sprinkles'],
          attributes: {
            Sabor: 'Chocolate',
            Tamaño: 'Individual',
            Decoración: ['Crema', 'Chocolate'],
            'Peso (kg)': 0.3,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Cupcakes de Vainilla',
          description: 'Set de 6 cupcakes de vainilla con frosting de queso crema. Decoración personalizada disponible.',
          price: 14.99,
          inStock: 35,
          slug: 'cupcakes-vainilla',
          images: ['https://imgs.search.brave.com/EYE3_jBYSOFcfZ_WSBC5x2c1bvNVGyD7Cbklr0wTnx8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jdXBj/YWtlc3l0YXJ0YXMu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE4LzAxL2N1cGNh/a2VzVmFpbmlsbGEx/LmpwZw'],
          category: 'Cupcakes',
          tags: ['cupcakes', 'vainilla', 'queso crema', 'personalizado'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Individual',
            Decoración: ['Crema'],
            'Peso (kg)': 0.3,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Medialunas de Manteca',
          description: 'Medialunas caseras de manteca, crocantes por fuera y suaves por dentro. Recién horneadas.',
          price: 1.2,
          inStock: 200,
          slug: 'medialunas-manteca',
          images: ['https://imgs.search.brave.com/1alTTv0Lg58cLCaVXVxV315Fz48jfaByu5DptUhKRPI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWct/Z2xvYmFsLmNwY2Ru/LmNvbS9yZWNpcGVz/L2IyZmEzMWMwYzE1/NmQ4YjMvMjQweDMy/MGNxODAvcGhvdG8u/anBn'],
          category: 'Panadería',
          tags: ['medialunas', 'manteca', 'caseras', 'tradicional'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Individual',
            Decoración: ['Sin decoración'],
            'Peso (kg)': 0.03,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Facturas Variadas',
          description: 'Mix de facturas surtidas: vigilantes, cañoncitos, bolas de fraile. Ideal para el desayuno.',
          price: 8.99,
          inStock: 50,
          slug: 'facturas-variadas',
          images: ['https://imgs.search.brave.com/ZtFQpeIKEHxfh_RtjO7kVip9YusJqjGyMzioVWoWbTs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvNDk2/NTY0OTE1L2VzL2Zv/dG8vcGFuLXktYnVu/cy5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9djhTenVaSWl0/akZMRzhRQ0pvc1lP/VEJDOHBEMVVfRkFp/SFNQSTVNdXVMZz0'],
          category: 'Panadería',
          tags: ['facturas', 'surtidas', 'tradicional', 'desayuno'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Individual',
            Decoración: ['Sin decoración'],
            'Peso (kg)': 0.5,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Torta de Cumpleaños Personalizada',
          description: 'Torta de cumpleaños personalizada con diseño a elección. Incluye decoración con fondant y velas.',
          price: 55.99,
          inStock: 8,
          slug: 'torta-cumpleanos-personalizada',
          images: ['https://imgs.search.brave.com/dRceSNXo2F-4BCiyoBn-Ingt2Kmxoa3Ry8Cz6ol7epM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzY0NDY3Mi1NTEE3/MTIzNDQyMjkzN18w/ODIwMjMtVi53ZWJw'],
          category: 'Especiales',
          tags: ['cumpleaños', 'personalizada', 'fondant', 'especial'],
          attributes: {
            Sabor: 'Chocolate',
            Tamaño: 'Grande (20 porciones)',
            Decoración: ['Fondant', 'Crema'],
            'Peso (kg)': 2.5,
            'Sin TACC': 'No',
          },
        },
        {
          title: 'Torta de Bodas',
          description: 'Torta elegante para bodas con diseño clásico. Disponible en varios sabores y tamaños.',
          price: 120.99,
          inStock: 5,
          slug: 'torta-bodas',
          images: ['https://imgs.search.brave.com/fn4HSHQ6HY2PH41t4M6iPFV-8cXLVbEJiIodKwkn2do/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/Xzg3MDk0MC1NTEE3/NTUzMjcwMDE0Nl8w/NDIwMjQtVi53ZWJw'],
          category: 'Especiales',
          tags: ['bodas', 'elegante', 'clásica', 'especial'],
          attributes: {
            Sabor: 'Vainilla',
            Tamaño: 'Grande (20 porciones)',
            Decoración: ['Fondant', 'Frutas'],
            'Peso (kg)': 4.0,
            'Sin TACC': 'No',
          },
        },
      ],
    },
    {
      name: 'Tecnología Avanzada',
      email: 'ventas@tecnologia.com',
      phone: '+5491123456789',
      domains: ['tecnologia.misproductos.shop', 'tecnologiaavanzada.com'],
      categories: ['Smartphones', 'Laptops', 'Tablets', 'Accesorios', 'Audio', 'Smart Home'],
      attributes: [
        {
          name: 'Marca',
          type: 'select',
          values: ['Apple', 'Samsung', 'Xiaomi', 'Huawei', 'Lenovo', 'Dell', 'HP'],
        },
        {
          name: 'Color',
          type: 'multiselect',
          values: ['Negro', 'Blanco', 'Gris', 'Azul', 'Rojo', 'Dorado', 'Plateado'],
        },
        {
          name: 'Almacenamiento (GB)',
          type: 'select',
          values: ['64', '128', '256', '512', '1024'],
        },
        {
          name: 'RAM (GB)',
          type: 'select',
          values: ['4', '6', '8', '12', '16', '32'],
        },
        {
          name: 'Garantía (meses)',
          type: 'number',
        },
      ],
      products: [
        {
          title: 'iPhone 15 Pro Max',
          description: 'El smartphone más avanzado de Apple con chip A17 Pro, cámara de 48MP y pantalla Super Retina XDR de 6.7".',
          price: 1299.99,
          inStock: 25,
          slug: 'iphone-15-pro-max',
          images: ['https://imgs.search.brave.com/vXqAMGnB61Yt7pvh8rLroU4IVxTk3yK-Tf562OeFbK4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLmVi/YXlpbWcuY29tL2lt/YWdlcy9nL1RhOEFB/T1N3WUtwbnd2SDgv/cy1sOTYwLmpwZw'],
          category: 'Smartphones',
          tags: ['iphone', 'apple', 'premium', 'pro'],
          attributes: {
            Marca: 'Apple',
            Color: ['Negro', 'Blanco', 'Azul', 'Dorado'],
            'Almacenamiento (GB)': '256',
            'RAM (GB)': '8',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Samsung Galaxy S24 Ultra',
          description: 'Smartphone flagship con S Pen, cámara de 200MP y pantalla Dynamic AMOLED 2X de 6.8".',
          price: 1199.99,
          inStock: 30,
          slug: 'samsung-galaxy-s24-ultra',
          images: ['https://imgs.search.brave.com/8Vdr2u13Y_sVE-k-H2ZluSxbIpla7cUZKUIJR5LHsZs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzYxNzc0Ni1NTEE5/Mjg3NzIxOTIwMF8w/OTIwMjUtVi53ZWJw'],
          category: 'Smartphones',
          tags: ['samsung', 'galaxy', 'ultra', 's-pen'],
          attributes: {
            Marca: 'Samsung',
            Color: ['Negro', 'Gris', 'Azul', 'Dorado'],
            'Almacenamiento (GB)': '512',
            'RAM (GB)': '12',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Xiaomi 14 Pro',
          description: 'Smartphone de alta gama con procesador Snapdragon 8 Gen 3 y cámara Leica de 50MP.',
          price: 899.99,
          inStock: 40,
          slug: 'xiaomi-14-pro',
          images: ['https://imgs.search.brave.com/KQ4h6P2ulVScUgOqhd22yAmDnTyLcRJnoVZrb0PFe3w/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hci5j/ZWx1bGFyZXMuY29t/L2ZvdG9zL3hpYW9t/aS1yZWRtaS1ub3Rl/LTE0LXByby05Nzc3/MC1nLWFsdC5qcGc'],
          category: 'Smartphones',
          tags: ['xiaomi', 'pro', 'leica', 'snapdragon'],
          attributes: {
            Marca: 'Xiaomi',
            Color: ['Negro', 'Blanco', 'Azul'],
            'Almacenamiento (GB)': '256',
            'RAM (GB)': '12',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'MacBook Pro 16" M3 Max',
          description: 'Laptop profesional con chip M3 Max, 36GB RAM unificada y pantalla Liquid Retina XDR de 16.2".',
          price: 3499.99,
          inStock: 15,
          slug: 'macbook-pro-16-m3-max',
          images: ['https://imgs.search.brave.com/-jtoe4IDZN5THhbDYrxFAuvAPAMcR5F_0MuIGyGZppM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/b2thbWFjLmNvbS8x/MDA2NTgtbWVkaXVt/X2RlZmF1bHQvbWFj/Ym9vay1wcm8tMTYt/MjAyMy1wdWNlLW0z/LW1heC1hcHBsZS1n/cHUtNDAtMTYtY29l/dXJzLTY0LWdvLXJh/bS00MS1naHouanBn'],
          category: 'Laptops',
          tags: ['macbook', 'apple', 'm3', 'pro'],
          attributes: {
            Marca: 'Apple',
            Color: ['Gris', 'Plateado'],
            'Almacenamiento (GB)': '1024',
            'RAM (GB)': '36',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'MacBook Air 15" M3',
          description: 'Laptop ultradelgada con chip M3, perfecta para trabajo y estudio. Pantalla Liquid Retina de 15.3".',
          price: 1499.99,
          inStock: 35,
          slug: 'macbook-air-15-m3',
          images: ['https://imgs.search.brave.com/pIQeWsvXS0rdbSc6P3-Ha2RYufrcJ9xPgT-A_zJ50gI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aG94dG9ubWFjcy5j/by51ay9jZG4vc2hv/cC9maWxlcy9hcHBs/ZS1tYWNib29rLWFp/ci0xNS1pbmNoLW1h/Y2Jvb2stYWlyLTE1/LWluY2gtbTMtc3Rh/cmxpZ2h0LTIwMjQt/Z29vZC00NjgzMTgx/MDQxMjg2MC5qcGc_/dj0xNzE3NTk3OTI4/JndpZHRoPTEwODA'],
          category: 'Laptops',
          tags: ['macbook', 'air', 'm3', 'ultradelgada'],
          attributes: {
            Marca: 'Apple',
            Color: ['Gris', 'Plateado', 'Dorado'],
            'Almacenamiento (GB)': '512',
            'RAM (GB)': '16',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Dell XPS 15',
          description: 'Laptop premium con Intel Core i9, 32GB RAM y pantalla OLED 4K de 15.6". Ideal para creativos.',
          price: 2499.99,
          inStock: 20,
          slug: 'dell-xps-15',
          images: ['https://imgs.search.brave.com/a07atX5s6i3JYi_NzRslkKSqNNdlHRBASTITyHYx5Tw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/MjEtODhYYXhhVUwu/anBn'],
          category: 'Laptops',
          tags: ['dell', 'xps', 'premium', 'creativo'],
          attributes: {
            Marca: 'Dell',
            Color: ['Gris', 'Negro'],
            'Almacenamiento (GB)': '1024',
            'RAM (GB)': '32',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Lenovo ThinkPad X1 Carbon',
          description: 'Laptop empresarial ultraliviana con Intel Core i7 y pantalla de 14". Durabilidad militar certificada.',
          price: 1899.99,
          inStock: 25,
          slug: 'lenovo-thinkpad-x1-carbon',
          images: ['https://imgs.search.brave.com/vusd-RwUUAEdqu-TK_w_vL2h8_AFOmeWDtc0w4lZHEs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wNC1v/ZnAuc3RhdGljLnB1/Yi9TaGFyZVJlc291/cmNlL25hL3Byb2R1/Y3RzL3RoaW5rcGFk/LzU2MHg0NTAvbGVu/b3ZvLXRoaW5rcGFk/LXgxLWNhcmJvbi1n/MTItMDEucG5n'],
          category: 'Laptops',
          tags: ['lenovo', 'thinkpad', 'empresarial', 'durable'],
          attributes: {
            Marca: 'Lenovo',
            Color: ['Negro'],
            'Almacenamiento (GB)': '512',
            'RAM (GB)': '16',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'iPad Pro 12.9" M2',
          description: 'Tablet profesional con chip M2, pantalla Liquid Retina XDR de 12.9" y soporte para Apple Pencil.',
          price: 1199.99,
          inStock: 30,
          slug: 'ipad-pro-12-9-m2',
          images: ['https://imgs.search.brave.com/GAdjJi2OaeiPVP8SyG8bqdrlZz3onUJobNZSweShyrI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9waG90/b3M1LmFwcGxlaW5z/aWRlci5jb20vcHJp/Y2VfZ3VpZGUvaXBh/ZC1wcm8tMTIuOS1p/bmNoLW0yLXBnLWhl/YWRlci5wbmc'],
          category: 'Tablets',
          tags: ['ipad', 'pro', 'm2', 'apple pencil'],
          attributes: {
            Marca: 'Apple',
            Color: ['Gris', 'Plateado'],
            'Almacenamiento (GB)': '256',
            'RAM (GB)': '8',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Samsung Galaxy Tab S9 Ultra',
          description: 'Tablet Android premium con pantalla Super AMOLED de 14.6" y S Pen incluido.',
          price: 999.99,
          inStock: 28,
          slug: 'samsung-galaxy-tab-s9-ultra',
          images: ['https://imgs.search.brave.com/sOBR3Sin5IaOiL5hkYDM37mk270pN88RccBYtvnKQng/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLmVi/YXlpbWcuY29tL3Ro/dW1icy9pbWFnZXMv/Zy9kRUVBQU9Td2xu/bGs1TEhEL3MtbDk2/MC53ZWJw'],
          category: 'Tablets',
          tags: ['samsung', 'galaxy', 'tablet', 's-pen'],
          attributes: {
            Marca: 'Samsung',
            Color: ['Negro', 'Gris'],
            'Almacenamiento (GB)': '256',
            'RAM (GB)': '12',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'AirPods Pro 2',
          description: 'Auriculares inalámbricos con cancelación activa de ruido y sonido espacial. Resistencia al agua IPX4.',
          price: 249.99,
          inStock: 60,
          slug: 'airpods-pro-2',
          images: ['https://imgs.search.brave.com/Xo_DTNBvZ-vefRSnM4kVVDCjGGvuf1xj6jfK4G8c7cc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZHNh/c3NldHMuYXBwbGUu/Y29tL2xpdmUvU1pM/RjBZTlYvaW1hZ2Vz/L3NwLzExMTg1MV9z/cDg4MC1haXJwb2Rz/LVByby0ybmQtZ2Vu/LnBuZw'],
          category: 'Audio',
          tags: ['airpods', 'apple', 'inalámbricos', 'cancelación ruido'],
          attributes: {
            Marca: 'Apple',
            Color: ['Blanco'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Sony WH-1000XM5',
          description: 'Auriculares over-ear con cancelación de ruido líder y batería de 30 horas. Sonido Hi-Res Audio.',
          price: 399.99,
          inStock: 45,
          slug: 'sony-wh-1000xm5',
          images: ['https://imgs.search.brave.com/L2HavtPrPLzzOlQT18kiNS8OSbbf3SnqSnINg-QKbyQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kYW0u/ZWxjb3J0ZWluZ2xl/cy5lcy9wcm9kdWN0/by93d3ctMDAxMDM4/NTQ1ODU4MzgzLTAx/LmpwZz9pbXBvbGlj/eT1SZXNpemUmd2lk/dGg9MTIwMCZoZWln/aHQ9MTIwMA'],
          category: 'Audio',
          tags: ['sony', 'over-ear', 'cancelación ruido', 'hi-res'],
          attributes: {
            Marca: 'Samsung',
            Color: ['Negro', 'Plateado'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Apple Watch Series 9',
          description: 'Smartwatch con chip S9 SiP, pantalla Always-On Retina y GPS. Monitoreo avanzado de salud.',
          price: 399.99,
          inStock: 50,
          slug: 'apple-watch-series-9',
          images: ['https://imgs.search.brave.com/2jQXz9yqqWYgLssfighazD3j874BlFlijnUDyZXAzfg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0cv/MDIvaW1nMTUvTWFy/Y2hFeWUvQ29tcGNo/YXJ0L0FwcGxlX1dh/dGNoX1Nlcmllc185/X0xURS5fQ0I1Nzgy/MjYwMTZfLnBuZw'],
          category: 'Accesorios',
          tags: ['apple watch', 'smartwatch', 'salud', 'gps'],
          attributes: {
            Marca: 'Apple',
            Color: ['Negro', 'Blanco', 'Rojo', 'Azul'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Cargador MagSafe',
          description: 'Cargador inalámbrico MagSafe compatible con iPhone y AirPods. Incluye cable USB-C.',
          price: 39.99,
          inStock: 100,
          slug: 'cargador-magsafe',
          images: ['https://imgs.search.brave.com/dmybbEvdFYGEdtEGpPJdrEGbPIn-2MktSHcnPPiVnv8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF85/OTYyNzAtTUxBNDcw/NzQ3ODAyNDdfMDgy/MDIxLU8ud2VicA'],
          category: 'Accesorios',
          tags: ['cargador', 'magsafe', 'inalámbrico', 'apple'],
          attributes: {
            Marca: 'Apple',
            Color: ['Blanco'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Google Nest Hub Max',
          description: 'Pantalla inteligente de 10" con Google Assistant, cámara y control de dispositivos smart home.',
          price: 229.99,
          inStock: 35,
          slug: 'google-nest-hub-max',
          images: ['https://imgs.search.brave.com/Sr3Yqje3oh-iCOO0v6G-gFyYSbjsEEjfsA2iq4TmTqE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90c2Ux/Lm1tLmJpbmcubmV0/L3RoL2lkL09JUC5k/WjlCZldKakFzbURn/RGNLWlVLRlZRSGFG/bj9waWQ9QXBp'],
          category: 'Smart Home',
          tags: ['google', 'nest', 'smart home', 'asistente'],
          attributes: {
            Marca: 'Samsung',
            Color: ['Blanco', 'Gris'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'Philips Hue Starter Kit',
          description: 'Kit de inicio con 3 bombillas LED inteligentes y puente. Control por app y asistentes de voz.',
          price: 199.99,
          inStock: 40,
          slug: 'philips-hue-starter-kit',
          images: ['https://imgs.search.brave.com/tdDXkp0HHK_aYvhzlo2zdEi413N8EMQ-MskPBkp14ZU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbGV2/ZW5nYW1lc2FyLmNv/bS9pbWcvUHVibGlj/LzExMzEtcHJvZHVj/dG8tbWVkaWRhcy1w/YXJhLW1lcmNhZG8t/bGlicmUtMjAyMi0x/Mi0yN3QxNzQ2NTAt/MDEzLTg2NTguanBn'],
          category: 'Smart Home',
          tags: ['philips', 'hue', 'smart home', 'led'],
          attributes: {
            Marca: 'Samsung',
            Color: ['Blanco', 'Multicolor'],
            'Almacenamiento (GB)': '64',
            'RAM (GB)': '4',
            'Garantía (meses)': 24,
          },
        },
        {
          title: 'Xiaomi Redmi Note 13 Pro',
          description: 'Smartphone de gama media-alta con cámara de 200MP y pantalla AMOLED de 6.67". Excelente relación precio-calidad.',
          price: 399.99,
          inStock: 55,
          slug: 'xiaomi-redmi-note-13-pro',
          images: ['https://imgs.search.brave.com/S6rWGPnTESWU5WSzS2S0zMrcTm8FSXpEOn9slOBrHAI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/Xzk4ODg3OC1DQlQ5/NjU0Nzk4NzY2NV8x/MDIwMjUtVi53ZWJw'],
          category: 'Smartphones',
          tags: ['xiaomi', 'redmi', 'gama media', 'cámara'],
          attributes: {
            Marca: 'Xiaomi',
            Color: ['Negro', 'Blanco', 'Azul'],
            'Almacenamiento (GB)': '256',
            'RAM (GB)': '12',
            'Garantía (meses)': 12,
          },
        },
        {
          title: 'HP Pavilion 15',
          description: 'Laptop versátil con AMD Ryzen 7, 16GB RAM y pantalla Full HD de 15.6". Ideal para trabajo y entretenimiento.',
          price: 899.99,
          inStock: 30,
          slug: 'hp-pavilion-15',
          images: ['https://imgs.search.brave.com/BBx4g6xjmkq6hRdjbgBl8G6v5Y7BtKLT9PD0Pc6l5Wo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF82/ODk5NTktTUxVNzIy/MjI5Njk3MDVfMTAy/MDIzLUYud2VicA'],
          category: 'Laptops',
          tags: ['hp', 'pavilion', 'versátil', 'amd'],
          attributes: {
            Marca: 'HP',
            Color: ['Gris', 'Plateado'],
            'Almacenamiento (GB)': '512',
            'RAM (GB)': '16',
            'Garantía (meses)': 12,
          },
        },
      ],
    },
    {
      name: 'Indumentaria Premium',
      email: 'contacto@indumentaria.com',
      phone: '+5491112345678',
      domains: ['indumentaria.misproductos.shop', 'indumentariapremium.com'],
      categories: ['Remeras', 'Pantalones', 'Buzos', 'Accesorios', 'Abrigos', 'Zapatillas'],
      attributes: [
        {
          name: 'Talla',
          type: 'select',
          values: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
        },
        {
          name: 'Color',
          type: 'multiselect',
          values: ['Negro', 'Blanco', 'Gris', 'Azul', 'Rojo', 'Verde', 'Beige', 'Marrón'],
        },
        {
          name: 'Material',
          type: 'select',
          values: ['Algodón', 'Poliéster', 'Algodón/Poliéster', 'Lino', 'Lana', 'Cuero'],
        },
        {
          name: 'Marca',
          type: 'text',
        },
        {
          name: 'Género',
          type: 'select',
          values: ['Hombre', 'Mujer', 'Unisex'],
        },
      ],
      products: [
        {
          title: 'Remera Básica Premium',
          description: 'Remera de algodón 100% premium, cómoda y duradera. Corte clásico y atemporal.',
          price: 29.99,
          inStock: 80,
          slug: 'remera-basica-premium',
          images: ['1740176-00-A_0_2000.jpg', '1740176-00-A_1.jpg'],
          category: 'Remeras',
          tags: ['básico', 'algodón', 'casual', 'premium'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Blanco', 'Gris', 'Azul'],
            Material: 'Algodón',
            Marca: 'Premium',
            Género: 'Unisex',
          },
        },
        {
          title: 'Remera Polo Clásica',
          description: 'Polo de algodón piqué con cuello y botones. Elegante y versátil para cualquier ocasión.',
          price: 45.99,
          inStock: 60,
          slug: 'remera-polo-clasica',
          images: ['1740507-00-A_0_2000.jpg', '1740507-00-A_1.jpg'],
          category: 'Remeras',
          tags: ['polo', 'clásica', 'elegante', 'versátil'],
          attributes: {
            Talla: 'L',
            Color: ['Blanco', 'Azul', 'Negro', 'Rojo'],
            Material: 'Algodón',
            Marca: 'Classic',
            Género: 'Unisex',
          },
        },
        {
          title: 'Remera Manga Larga',
          description: 'Remera de manga larga con cuello redondo. Perfecta para capas o uso individual.',
          price: 35.99,
          inStock: 70,
          slug: 'remera-manga-larga',
          images: ['1740250-00-A_0_2000.jpg', '1740250-00-A_1.jpg'],
          category: 'Remeras',
          tags: ['manga larga', 'cómoda', 'versátil'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Gris', 'Blanco'],
            Material: 'Algodón',
            Marca: 'Comfort',
            Género: 'Unisex',
          },
        },
        {
          title: 'Pantalón Cargo',
          description: 'Pantalón cargo con múltiples bolsillos, ideal para uso diario y actividades al aire libre.',
          price: 55.99,
          inStock: 50,
          slug: 'pantalon-cargo',
          images: ['1740280-00-A_0_2000.jpg', '1740280-00-A_1.jpg'],
          category: 'Pantalones',
          tags: ['cargo', 'casual', 'práctico', 'bolsillos'],
          attributes: {
            Talla: 'L',
            Color: ['Negro', 'Gris', 'Beige', 'Verde'],
            Material: 'Algodón/Poliéster',
            Marca: 'Urban',
            Género: 'Hombre',
          },
        },
        {
          title: 'Pantalón Chino',
          description: 'Pantalón chino clásico en corte regular. Elegante y cómodo para oficina o casual.',
          price: 49.99,
          inStock: 65,
          slug: 'pantalon-chino',
          images: ['1741416-00-A_0_2000.jpg', '1741416-00-A_1.jpg'],
          category: 'Pantalones',
          tags: ['chino', 'clásico', 'elegante', 'oficina'],
          attributes: {
            Talla: 'M',
            Color: ['Beige', 'Gris', 'Azul', 'Marrón'],
            Material: 'Algodón',
            Marca: 'Formal',
            Género: 'Unisex',
          },
        },
        {
          title: 'Jeans Slim Fit',
          description: 'Jeans de corte slim fit con elastano para mayor comodidad. Denim de alta calidad.',
          price: 79.99,
          inStock: 45,
          slug: 'jeans-slim-fit',
          images: ['7654393-00-A_2_2000.jpg', '7654393-00-A_3.jpg'],
          category: 'Pantalones',
          tags: ['jeans', 'slim fit', 'denim', 'elastano'],
          attributes: {
            Talla: 'L',
            Color: ['Azul', 'Negro'],
            Material: 'Algodón',
            Marca: 'Denim',
            Género: 'Unisex',
          },
        },
        {
          title: 'Buzo con Capucha',
          description: 'Buzo abrigado con capucha ajustable, perfecto para el invierno. Bolsillo canguro incluido.',
          price: 75.99,
          inStock: 40,
          slug: 'buzo-capucha',
          images: ['1703767-00-A_0_2000.jpg', '1703767-00-A_1.jpg'],
          category: 'Buzos',
          tags: ['abrigado', 'invierno', 'capucha', 'cómodo'],
          attributes: {
            Talla: 'XL',
            Color: ['Gris', 'Negro', 'Azul', 'Rojo'],
            Material: 'Algodón/Poliéster',
            Marca: 'Warm',
            Género: 'Unisex',
          },
        },
        {
          title: 'Buzo Sin Capucha',
          description: 'Buzo clásico sin capucha, ideal para capas. Corte regular y cómodo.',
          price: 65.99,
          inStock: 50,
          slug: 'buzo-sin-capucha',
          images: ['1740176-00-A_0_2000.jpg', '1740176-00-A_1.jpg'],
          category: 'Buzos',
          tags: ['buzo', 'clásico', 'sin capucha', 'capas'],
          attributes: {
            Talla: 'M',
            Color: ['Gris', 'Negro', 'Blanco'],
            Material: 'Algodón/Poliéster',
            Marca: 'Classic',
            Género: 'Unisex',
          },
        },
        {
          title: 'Abrigo de Invierno',
          description: 'Abrigo largo de invierno con capucha desmontable. Impermeable y con relleno térmico.',
          price: 149.99,
          inStock: 30,
          slug: 'abrigo-invierno',
          images: ['1740507-00-A_0_2000.jpg', '1740507-00-A_1.jpg'],
          category: 'Abrigos',
          tags: ['abrigo', 'invierno', 'impermeable', 'térmico'],
          attributes: {
            Talla: 'L',
            Color: ['Negro', 'Gris', 'Azul'],
            Material: 'Poliéster',
            Marca: 'Winter',
            Género: 'Unisex',
          },
        },
        {
          title: 'Chaqueta de Cuero',
          description: 'Chaqueta de cuero genuino con forro interno. Estilo clásico y atemporal.',
          price: 299.99,
          inStock: 20,
          slug: 'chaqueta-cuero',
          images: ['1740250-00-A_0_2000.jpg', '1740250-00-A_1.jpg'],
          category: 'Abrigos',
          tags: ['cuero', 'chaqueta', 'clásica', 'premium'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Marrón'],
            Material: 'Cuero',
            Marca: 'Leather',
            Género: 'Unisex',
          },
        },
        {
          title: 'Zapatillas Deportivas',
          description: 'Zapatillas deportivas con tecnología de amortiguación. Ideales para running y entrenamiento.',
          price: 89.99,
          inStock: 60,
          slug: 'zapatillas-deportivas',
          images: ['1740280-00-A_0_2000.jpg', '1740280-00-A_1.jpg'],
          category: 'Zapatillas',
          tags: ['zapatillas', 'deportivas', 'running', 'amortiguación'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Blanco', 'Gris', 'Azul'],
            Material: 'Poliéster',
            Marca: 'Sport',
            Género: 'Unisex',
          },
        },
        {
          title: 'Zapatillas Urbanas',
          description: 'Zapatillas urbanas estilo casual. Cómodas y versátiles para el día a día.',
          price: 69.99,
          inStock: 75,
          slug: 'zapatillas-urbanas',
          images: ['1741416-00-A_0_2000.jpg', '1741416-00-A_1.jpg'],
          category: 'Zapatillas',
          tags: ['zapatillas', 'urbanas', 'casual', 'cómodas'],
          attributes: {
            Talla: 'L',
            Color: ['Blanco', 'Negro', 'Gris'],
            Material: 'Poliéster',
            Marca: 'Urban',
            Género: 'Unisex',
          },
        },
        {
          title: 'Gorra Snapback',
          description: 'Gorra snapback ajustable con visera curva. Diseño clásico y versátil.',
          price: 24.99,
          inStock: 100,
          slug: 'gorra-snapback',
          images: ['7654393-00-A_2_2000.jpg', '7654393-00-A_3.jpg'],
          category: 'Accesorios',
          tags: ['gorra', 'snapback', 'ajustable', 'clásica'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Blanco', 'Gris', 'Azul', 'Rojo'],
            Material: 'Poliéster',
            Marca: 'Cap',
            Género: 'Unisex',
          },
        },
        {
          title: 'Mochila Urbana',
          description: 'Mochila urbana con múltiples compartimentos y bolsillo para laptop. Resistente y funcional.',
          price: 59.99,
          inStock: 55,
          slug: 'mochila-urbana',
          images: ['1703767-00-A_0_2000.jpg', '1703767-00-A_1.jpg'],
          category: 'Accesorios',
          tags: ['mochila', 'urbana', 'laptop', 'funcional'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Gris', 'Azul'],
            Material: 'Poliéster',
            Marca: 'Bag',
            Género: 'Unisex',
          },
        },
        {
          title: 'Cinturón de Cuero',
          description: 'Cinturón de cuero genuino con hebilla metálica. Disponible en varios colores.',
          price: 34.99,
          inStock: 80,
          slug: 'cinturon-cuero',
          images: ['1740176-00-A_0_2000.jpg', '1740176-00-A_1.jpg'],
          category: 'Accesorios',
          tags: ['cinturón', 'cuero', 'clásico', 'elegante'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Marrón'],
            Material: 'Cuero',
            Marca: 'Leather',
            Género: 'Unisex',
          },
        },
        {
          title: 'Remera Oversized',
          description: 'Remera de corte oversized, tendencia actual. Cómoda y con estilo urbano.',
          price: 32.99,
          inStock: 70,
          slug: 'remera-oversized',
          images: ['1740507-00-A_0_2000.jpg', '1740507-00-A_1.jpg'],
          category: 'Remeras',
          tags: ['oversized', 'tendencia', 'urbano', 'cómoda'],
          attributes: {
            Talla: 'L',
            Color: ['Negro', 'Blanco', 'Gris'],
            Material: 'Algodón',
            Marca: 'Trend',
            Género: 'Unisex',
          },
        },
        {
          title: 'Pantalón Deportivo',
          description: 'Pantalón deportivo con cintura elástica y bolsillos. Perfecto para entrenar o relajarse.',
          price: 44.99,
          inStock: 60,
          slug: 'pantalon-deportivo',
          images: ['1740250-00-A_0_2000.jpg', '1740250-00-A_1.jpg'],
          category: 'Pantalones',
          tags: ['deportivo', 'elástico', 'cómodo', 'entrenamiento'],
          attributes: {
            Talla: 'M',
            Color: ['Negro', 'Gris', 'Azul'],
            Material: 'Poliéster',
            Marca: 'Sport',
            Género: 'Unisex',
          },
        },
      ],
    },
    {
      name: 'Cursos Online',
      email: 'info@curs online.com',
      phone: '+5491123456789',
      domains: ['cursosonline.misproductos.shop', 'cursos.com'],
      categories: ['Programación', 'Diseño', 'Marketing', 'Negocios', 'Idiomas', 'Fotografía'],
      attributes: [
        {
          name: 'Duración (horas)',
          type: 'number',
        },
        {
          name: 'Nivel',
          type: 'select',
          values: ['Principiante', 'Intermedio', 'Avanzado'],
        },
        {
          name: 'Modalidad',
          type: 'select',
          values: ['Online', 'Grabado', 'En Vivo'],
        },
        {
          name: 'Certificado',
          type: 'select',
          values: ['Sí', 'No'],
        },
        {
          name: 'Idioma',
          type: 'select',
          values: ['Español', 'Inglés', 'Portugués'],
        },
      ],
      products: [
        {
          title: 'Curso Completo de React y Next.js',
          description: 'Aprende React desde cero hasta avanzado, incluyendo Next.js 14, Server Components, y las últimas características. Incluye proyectos prácticos.',
          price: 89.99,
          inStock: 999,
          slug: 'curso-react-nextjs',
          images: ['https://imgs.search.brave.com/2ijyU7ySdj2B7SEgV1hAIkT0GQpm9qVUwIQ4_87ZmKw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMtbWVkaWEuaG90/bWFydC5jb20vQThD/QTZEVTNBRmtrYldU/czF1SjZwc3k1R1BN/PS8zMDB4MzAwL3Nt/YXJ0L2ZpbHRlcnM6/Zm9ybWF0KHdlYnAp/OmJhY2tncm91bmRf/Y29sb3Iod2hpdGUp/L2hvdG1hcnQvcHJv/ZHVjdF9waWN0dXJl/cy8xNDllZjU5OC1m/ZDE3LTRjYTQtODQ3/MC1iYjRhYzNlY2M0/OTYvYXZhdGFyaG90/bWFydHJlYWN0bmV4/dC5wbmc_dz05MjA'],
          category: 'Programación',
          tags: ['react', 'nextjs', 'javascript', 'frontend'],
          attributes: {
            'Duración (horas)': 40,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Masterclass de TypeScript',
          description: 'Domina TypeScript desde lo básico hasta técnicas avanzadas. Tipos, genéricos, decoradores y mejores prácticas.',
          price: 69.99,
          inStock: 999,
          slug: 'masterclass-typescript',
          images: ['https://imgs.search.brave.com/u1IbX9fsQ1-WmIxFiVnLj7y583vL_8uD3cH9zvBoFM0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuY3RmYXNzZXRz/Lm5ldC9hcTEzbHds/NjYxNnEvM0pMNFAx/bm1mbkg0MjVSeGts/NG41VS82MGMzNTdm/MzU0ZDlhOTI4NDQx/ODczN2IzZTQyMzk3/MS9Db3Vyc2VfVGh1/bWJuYWlsXy1fVHlw/ZVNjcmlwdF85LnBu/Zz93PTUwMCZmbT13/ZWJw'],
          category: 'Programación',
          tags: ['typescript', 'programación', 'javascript', 'avanzado'],
          attributes: {
            'Duración (horas)': 25,
            Nivel: 'Avanzado',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Python para Data Science',
          description: 'Curso completo de Python aplicado a Data Science. Pandas, NumPy, Matplotlib y Machine Learning básico.',
          price: 99.99,
          inStock: 999,
          slug: 'python-data-science',
          images: ['https://imgs.search.brave.com/BENTvvE-uvpFTATCfJ4gbe2KbgnhURA4uC-idwwXn_o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHV0a2l0LmNvbS9z/dG9yYWdlL21lZGlh/L3BhY2thZ2VzLzMz/Ny8zMzctcHJvZ3Jh/bW1pZXJlbi1taXQt/cHl0aG9uLWRlci1h/bmZhZW5nZXIta3Vy/cy1tYWluLW1lZC53/ZWJw'],
          category: 'Programación',
          tags: ['python', 'data science', 'machine learning', 'pandas'],
          attributes: {
            'Duración (horas)': 50,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Diseño UI/UX con Figma',
          description: 'https://imgs.search.brave.com/H9NWrmbOX01WdQlFZGdIEyuONnzmKVuv02Msh2o7Z8U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9vcnN5/cy1sZW1hZy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjQv/MDIvRmlnbWEuanBn',
          price: 79.99,
          inStock: 999,
          slug: 'diseno-ui-ux-figma',
          images: ['https://imgs.search.brave.com/P5aVJpON_WHu3BNLHzkOYRiBrOyMnCLsWk2PK1_DRyY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMuc2tpbGxzaGFy/ZS5jb20vdXBsb2Fk/cy9wcm9qZWN0LzQx/MzA5MS9jb3Zlcl84/MDBfNjdmMzc4M2Jk/MzhlYzQ1MTgzMzQz/Y2RkNmUyMmFmYmQu/cG5n'],
          category: 'Diseño',
          tags: ['figma', 'ui', 'ux', 'diseño'],
          attributes: {
            'Duración (horas)': 30,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Adobe Photoshop Avanzado',
          description: 'Técnicas avanzadas de Photoshop para retoque fotográfico, composición y diseño gráfico profesional.',
          price: 89.99,
          inStock: 999,
          slug: 'photoshop-avanzado',
          images: ['https://imgs.search.brave.com/e36aPf5hDtnRj-1_7jSYUvnQw3P3sdLjnRJJ90BG7z0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bGVuLmVzL3VwbG9h/ZHMvbGVuL3Byb2R1/Y3Rvcy9tXzMxNjBf/cGhvdG9zaG9wLWF2/YW56YWRvLmpwZw'],
          category: 'Diseño',
          tags: ['photoshop', 'retoque', 'diseño gráfico', 'avanzado'],
          attributes: {
            'Duración (horas)': 35,
            Nivel: 'Avanzado',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Marketing Digital Completo',
          description: 'Estrategias de marketing digital: SEO, SEM, redes sociales, email marketing y análisis de datos.',
          price: 119.99,
          inStock: 999,
          slug: 'marketing-digital-completo',
          images: ['https://imgs.search.brave.com/9u0K6uNTP-QTZ9UUFRZ2DrilExAYkvqJgEMvl4Qi25c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvOTU2/NDI2MzMwL2VzL3Zl/Y3Rvci9jb25jZXB0/by1kZS1tYXJrZXRp/bmctZGlnaXRhbC5q/cGc_cz02MTJ4NjEy/Jnc9MCZrPTIwJmM9/Y0dMa0phcV9NczJM/TWg0SEJYZEJxU21H/Sktqb0x6WGQyX01Q/dWFEcDIxVT0'],
          category: 'Marketing',
          tags: ['marketing', 'seo', 'redes sociales', 'digital'],
          attributes: {
            'Duración (horas)': 45,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Instagram Marketing',
          description: 'Domina Instagram para negocios: contenido, stories, reels, publicidad y crecimiento orgánico.',
          price: 59.99,
          inStock: 999,
          slug: 'instagram-marketing',
          images: ['https://imgs.search.brave.com/Ty0uPtRg0otOvZ0JlZEabG__UYjmKIEWtGAACjf2rjs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5kZXNpZ25ydXNo/LmNvbS9hcnRpY2xl/cy83NTI3NzcvY29u/dmVyc2lvbnMvOC1J/bnN0YWdyYW0tTWFy/a2V0aW5nLVN0cmF0/ZWdpZXMtZGV0YWls/cy5qcGc'],
          category: 'Marketing',
          tags: ['instagram', 'marketing', 'redes sociales', 'contenido'],
          attributes: {
            'Duración (horas)': 20,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Emprendimiento desde Cero',
          description: 'Guía completa para crear y lanzar tu negocio. Modelos de negocio, validación, financiamiento y crecimiento.',
          price: 99.99,
          inStock: 999,
          slug: 'emprendimiento-desde-cero',
          images: ['https://imgs.search.brave.com/1cMwjD4arrL-e0EWovIquOmJl4vnDk72kDu_h5YWbMs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbXBy/ZW5kZWRpZ2l0YWxh/aG9yYS5jb20vd3At/Y29udGVudC91cGxv/YWRzLzIwMjUvMDMv/Qmx1ZS1GdXR1cmlz/dGljLUJ1c2luZXNz/LVByZXNlbnRhdGlv/bi5qcGc'],
          category: 'Negocios',
          tags: ['emprendimiento', 'negocios', 'startup', 'financiamiento'],
          attributes: {
            'Duración (horas)': 40,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Finanzas Personales',
          description: 'Aprende a gestionar tus finanzas personales: presupuesto, inversiones, ahorro y planificación financiera.',
          price: 69.99,
          inStock: 999,
          slug: 'finanzas-personales',
          images: ['https://imgs.search.brave.com/tnhJl1R4QjK4gHDXLmAv2BgNxbLvElPGBq-bghv1Wbo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbGVh/cm5pbmcuYnVyc2Vu/LmNvbS5wZS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAxOC8wOS9D/dXJzby1vbmxpbmUt/RmluYW56YXMtUGVy/c29uYWxlcy5qcGc'],
          category: 'Negocios',
          tags: ['finanzas', 'inversiones', 'ahorro', 'personal'],
          attributes: {
            'Duración (horas)': 25,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Inglés para Principiantes',
          description: 'Curso completo de inglés desde cero. Gramática, vocabulario, pronunciación y conversación básica.',
          price: 79.99,
          inStock: 999,
          slug: 'ingles-principiantes',
          images: ['https://imgs.search.brave.com/PfMjKeyuJYJG4UkI08hM9iXRGV6AVLnXiCOjeXO4bJk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jbGFz/ZWZsaXguaW8vX25l/eHQvaW1hZ2U_dXJs/PWh0dHBzOi8vcmVz/LmNsb3VkaW5hcnku/Y29tL2NsYXNlZmxp/eC9pbWFnZS91cGxv/YWQvdjE2NDY3ODcx/NjYvY291cnNlcy9j/dXJzby1kZS1pbmds/ZXMtMi1ibV9kd2c3/cm4uanBnJnc9Mzg0/MCZxPTc1'],
          category: 'Idiomas',
          tags: ['inglés', 'idiomas', 'principiante', 'gramática'],
          attributes: {
            'Duración (horas)': 60,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Inglés Avanzado',
          description: 'Perfecciona tu inglés con técnicas avanzadas de conversación, escritura académica y negocios.',
          price: 89.99,
          inStock: 999,
          slug: 'ingles-avanzado',
          images: ['https://imgs.search.brave.com/zQ95flABYSW2sIuZCHp6UD8vYTjxS1iQm76P26ddEWc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZnJycS51dG4uZWR1/LmFyL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzEyL2ltZ19D/VVJTTy1pbmdsZXMt/YXZhbnphZG8tMTAy/NHgxMDI0LmpwZw'],
          category: 'Idiomas',
          tags: ['inglés', 'avanzado', 'conversación', 'negocios'],
          attributes: {
            'Duración (horas)': 50,
            Nivel: 'Avanzado',
            Modalidad: 'En Vivo',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Fotografía Digital',
          description: 'Aprende los fundamentos de la fotografía digital: composición, iluminación, edición y técnicas profesionales.',
          price: 89.99,
          inStock: 999,
          slug: 'fotografia-digital',
          images: ['https://imgs.search.brave.com/dZhl_oWXsBYJmELkpRjn6gOvn5GTQ3puW6RPz5BXHi8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lc2N1/ZWxhZmludGVjaC5j/b20vd3AtY29udGVu/dC91cGxvYWRzL2N1/cnNvLWRlLWZvdG9n/cmFmaWEtZGlnaXRh/bC5qcGc'],
          category: 'Fotografía',
          tags: ['fotografía', 'digital', 'composición', 'edición'],
          attributes: {
            'Duración (horas)': 35,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Fotografía de Retrato',
          description: 'Especialización en fotografía de retrato: iluminación de estudio, poses y edición profesional.',
          price: 99.99,
          inStock: 999,
          slug: 'fotografia-retrato',
          images: ['https://imgs.search.brave.com/87oJHWpLQG6NsiJuGJTjeJ7rNi1E7Bip3waPMxIClNs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb211/bmlkYWQuc2VyZXku/YXJ0L3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIwLzA0L0N1cnNv/LWRlLVJldHJhdG8t/UmVhbGlzdGEtMS5q/cGc'],
          category: 'Fotografía',
          tags: ['fotografía', 'retrato', 'iluminación', 'estudio'],
          attributes: {
            'Duración (horas)': 30,
            Nivel: 'Avanzado',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Node.js y Express',
          description: 'Desarrollo backend con Node.js y Express. APIs RESTful, autenticación, bases de datos y deployment.',
          price: 94.99,
          inStock: 999,
          slug: 'nodejs-express',
          images: ['https://imgs.search.brave.com/vPzHm-g3mEB1Njfd2bNRE7F1bzcUXe588BlOJTVikSc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jYW1v/LmdpdGh1YnVzZXJj/b250ZW50LmNvbS80/ZDE3ZDVhYjRkYzBm/OTNjYWMxMTY4MDk4/NDFhOWMxMzBiZThl/YzA2NDJkMDlmZGI3/MWY0NzJiNzM0ODI4/MDkyLzY4NzQ3NDcw/NzMzYTJmMmY2NzY5/NzQ2ODc1NjIyZDcw/NzI2ZjY0NzU2Mzc0/Njk2ZjZlMmQ3NTcz/NjU3MjJkNjE3Mzcz/NjU3NDJkMzYzMjMx/MzA2NDY2MmU3MzMz/MmU2MTZkNjE3YTZm/NmU2MTc3NzMyZTYz/NmY2ZDJmMzEzNTM2/MzEzOTM1MzUyZjMy/MzUzNDM4MzAzNjM0/MzIzOTJkMzg2NjY2/MzczNDMzMzEzNjJk/NjQzNDM5NjUyZDM0/MzMzNTM4MmQzODYy/MzE2NTJkMzAzNzY0/Mzc2MjM1NjEzNjM0/NjU2NDM0MmU2YTcw/NjU2Nw'],
          category: 'Programación',
          tags: ['nodejs', 'express', 'backend', 'api'],
          attributes: {
            'Duración (horas)': 38,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Vue.js 3 Completo',
          description: 'Curso completo de Vue.js 3 con Composition API, Pinia, Vue Router y las mejores prácticas.',
          price: 84.99,
          inStock: 999,
          slug: 'vuejs-3-completo',
          images: ['https://imgs.search.brave.com/Hm-X6VTL-dujK0GCVluYvHJMq-U8rW5KP9EUGFmxdks/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdG9y/YWdlLmdvb2dsZWFw/aXMuY29tL2V0aS1h/Y2FkZW15L2NvdXJz/ZXMvY3Vyc28tZ3Jh/dHVpdG8taW50cm9k/dWNhby1hby12dWUu/anMtMy5wbmc'],
          category: 'Programación',
          tags: ['vuejs', 'frontend', 'javascript', 'composition api'],
          attributes: {
            'Duración (horas)': 32,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Illustrator para Diseñadores',
          description: 'Domina Adobe Illustrator para diseño vectorial, logos, ilustraciones y gráficos profesionales.',
          price: 79.99,
          inStock: 999,
          slug: 'illustrator-disenadores',
          images: ['https://imgs.search.brave.com/Ln-0N8rNOy3gGm47d0EumooPRkU9jcGyCsrFIalE6C0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb29s/cHJpbnRzLmNvbS5t/eC93cC1jb250ZW50/L3VwbG9hZHMvMjAy/My8wMi9DdXJzby1B/ZG9iZS1JbGx1c3Ry/YXRvci5qcGc'],
          category: 'Diseño',
          tags: ['illustrator', 'vectorial', 'logos', 'diseño'],
          attributes: {
            'Duración (horas)': 28,
            Nivel: 'Intermedio',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
        {
          title: 'Copywriting para Redes Sociales',
          description: 'Aprende a escribir textos persuasivos para redes sociales que convierten y generan engagement.',
          price: 64.99,
          inStock: 999,
          slug: 'copywriting-redes-sociales',
          images: ['https://imgs.search.brave.com/hMTHkhZhLpjBckAPoyDDpBW53MqoRjpDWEcPuk_MhKY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lc2N1/ZWxhLm1hcmtldGlu/Z2FuZHdlYi5lcy93/cC1jb250ZW50L3Vw/bG9hZHMvQ3Vyc28t/Y29weXdyaXRpbmct/SU1BR0VOLmpwZw'],
          category: 'Marketing',
          tags: ['copywriting', 'redes sociales', 'contenido', 'persuasión'],
          attributes: {
            'Duración (horas)': 18,
            Nivel: 'Principiante',
            Modalidad: 'Grabado',
            Certificado: 'Sí',
            Idioma: 'Español',
          },
        },
      ],
    },
    {
      name: 'Librería El Saber',
      email: 'ventas@libreriaelsaber.com',
      phone: '+5491134567890',
      domains: ['libreria.misproductos.shop', 'libreriaelsaber.com'],
      logo: 'https://imgs.search.brave.com/o6SdOOWNuAm-SGKz1vRlPcMOdeueS4CN0OOa9qqW8bY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzQzLzRk/LzcxLzQzNGQ3MWI2/N2UyNGM0NGM0MjZj/OGJkMDQzM2YwNGU2/LmpwZw',
      categories: ['Ficción', 'No Ficción', 'Infantil', 'Juvenil', 'Ciencia', 'Historia', 'Biografías', 'Autoayuda'],
      attributes: [
        {
          name: 'Autor',
          type: 'select',
          values: ['Gabriel García Márquez', 'Dan Brown', 'George Orwell', 'Yuval Noah Harari', 'Antoine de Saint-Exupéry', 'J.K. Rowling', 'Stephen Hawking', 'Sun Tzu'],
        },
        {
          name: 'Editorial',
          type: 'select',
          values: ['Penguin Random House', 'Planeta', 'Alfaguara', 'Sudamericana', 'Tusquets', 'Anagrama', 'Debolsillo', 'Paidós'],
        },
        {
          name: 'Formato',
          type: 'select',
          values: ['Tapa blanda', 'Tapa dura', 'Ebook', 'Audiolibro'],
        },
        {
          name: 'Idioma',
          type: 'select',
          values: ['Español', 'Inglés', 'Portugués'],
        },
        {
          name: 'Páginas',
          type: 'number',
        },
      ],
      products: [
        {
          title: 'Cien Años de Soledad',
          description: 'La obra maestra de Gabriel García Márquez. La épica historia de la familia Buendía a lo largo de siete generaciones en el mítico pueblo de Macondo.',
          price: 24.99,
          inStock: 50,
          slug: 'cien-anos-soledad',
          images: ['https://imgs.search.brave.com/9JSUIuXlIowchUecdAvsnboEydIW_1ch_607C9yvfoM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9waWNz/LmZpbG1hZmZpbml0/eS5jb20vY2llbl9h/bm9zX2RlX3NvbGVk/YWQtNjA2NjMwMjE2/LW1tZWQuanBn'],
          category: 'Ficción',
          tags: ['garcía márquez', 'realismo mágico', 'clásico', 'literatura latinoamericana'],
          attributes: {
            Autor: 'Gabriel García Márquez',
            Editorial: 'Sudamericana',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 471,
          },
        },
        {
          title: 'El Código Da Vinci',
          description: 'Thriller de misterio y conspiración que sigue a Robert Langdon mientras descubre secretos ocultos en obras de arte del Louvre.',
          price: 19.99,
          inStock: 75,
          slug: 'codigo-da-vinci',
          images: ['https://imgs.search.brave.com/uJaXBvbdBFyFCEsaAM0InbFZCy3C73o7VkOTPmVrMrU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50djIudGFwLWNv/bW1lcmNlLmNvbS9j/b3Zlci9sYXJnZS85/Nzg4NDA4MTc1NzI4/XzEuanBnP2lkX2Nv/bT0xMTU2JmJhY2s9/ZmFkMmUx'],
          category: 'Ficción',
          tags: ['thriller', 'misterio', 'conspiración', 'bestseller'],
          attributes: {
            Autor: 'Dan Brown',
            Editorial: 'Planeta',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 656,
          },
        },
        {
          title: '1984',
          description: 'Distopía clásica de George Orwell sobre un futuro totalitario donde el Gran Hermano vigila cada movimiento. Una obra esencial de la literatura.',
          price: 16.99,
          inStock: 60,
          slug: '1984-orwell',
          images: ['https://imgs.search.brave.com/A11rdm3diby-aM-K3DFM2eEhhlakwgE7dPvTveXVsss/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzYyOTU3Ny1NTEE4/NzQ1MDQ4MDIzOF8w/NzIwMjUtVi53ZWJw'],
          category: 'Ficción',
          tags: ['distopía', 'orwell', 'clásico', 'política'],
          attributes: {
            Autor: 'George Orwell',
            Editorial: 'Debolsillo',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 352,
          },
        },
        {
          title: 'Sapiens: De Animales a Dioses',
          description: 'Una breve historia de la humanidad que explora cómo el Homo sapiens conquistó el mundo. Del autor Yuval Noah Harari.',
          price: 22.99,
          inStock: 45,
          slug: 'sapiens-harari',
          images: ['https://imgs.search.brave.com/5em6HNwcqXvOLux0HMycKtuqSTOn4nD2WhgPg1MXREo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YWdhcGVhLmNvbS9F/ZGl0b3JpYWwtRGVi/YXRlL0RlLWFuaW1h/bGVzLWEtZGlvc2Vz/LVNhcGllbnMtLWk3/bjEyNjYyNjkzLmpw/Zw'],
          category: 'No Ficción',
          tags: ['historia', 'antropología', 'ciencia', 'bestseller'],
          attributes: {
            Autor: 'Yuval Noah Harari',
            Editorial: 'Debate',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 496,
          },
        },
        {
          title: 'El Principito',
          description: 'La conmovedora historia del pequeño príncipe que viaja por diferentes planetas. Una fábula filosófica para todas las edades.',
          price: 12.99,
          inStock: 100,
          slug: 'principito',
          images: ['https://imgs.search.brave.com/iOmuJ042-y_PuLWuxjj8uQ-YVmB2YHhNy6v9Xs0mPaE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDF5dG5jcnFDZUwu/anBn'],
          category: 'Infantil',
          tags: ['infantil', 'filosofía', 'clásico', 'ilustrado'],
          attributes: {
            Autor: 'Antoine de Saint-Exupéry',
            Editorial: 'Emecé',
            Formato: 'Tapa dura',
            Idioma: 'Español',
            Páginas: 96,
          },
        },
        {
          title: 'Harry Potter y la Piedra Filosofal',
          description: 'El primer libro de la saga más famosa de la literatura juvenil. Acompaña a Harry en su primer año en Hogwarts.',
          price: 18.99,
          inStock: 80,
          slug: 'harry-potter-piedra-filosofal',
          images: ['https://imgs.search.brave.com/39qDlJbf3vZ9oR8ccF4A_knqqU3vIfyHTqqqaFw6tp4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9sb3M0/MC5jb20vcmVzaXpl/ci92Mi80RkFFRFNO/WlBCTFVESkZKRUZY/V0o0T1RRTS5qcGc_/YXV0aD1iNmVkNGM4/Y2M0MTg0M2VmMTZk/ZmZmM2U4YWFhMmJj/OTc2NGUxOTdiNjBi/ODY2YzliMzllZWFi/OTg0MjQ5ZWQ5'],
          category: 'Juvenil',
          tags: ['fantasía', 'juvenil', 'magia', 'bestseller'],
          attributes: {
            Autor: 'J.K. Rowling',
            Editorial: 'Salamandra',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 264,
          },
        },
        {
          title: 'Breve Historia del Tiempo',
          description: 'Stephen Hawking explica los misterios del universo de forma accesible. Desde el Big Bang hasta los agujeros negros.',
          price: 21.99,
          inStock: 40,
          slug: 'breve-historia-tiempo',
          images: ['https://imgs.search.brave.com/UnqlV7LratRgPriDyEX2Qci2Us1Te97mxlkqOcnQ0IM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50djIudGFwLWNv/bW1lcmNlLmNvbS9j/b3Zlci9sYXJnZS85/Nzg4NDIwNjUxOTk2/XzEuanBnP2lkX2Nv/bT0xMTU2JmJhY2s9/ZmFkMmUx'],
          category: 'Ciencia',
          tags: ['ciencia', 'física', 'astronomía', 'hawking'],
          attributes: {
            Autor: 'Stephen Hawking',
            Editorial: 'Crítica',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 256,
          },
        },
        {
          title: 'El Arte de la Guerra',
          description: 'Tratado militar chino escrito por Sun Tzu hace más de 2500 años. Aplicable a estrategia, negocios y vida personal.',
          price: 14.99,
          inStock: 90,
          slug: 'arte-guerra',
          images: ['https://imgs.search.brave.com/raK8BSCXUPf8Vnp7y5JwX-B7Ota_xI5qz71RPoXH6xQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzYxNnhadXcwNmNM/LmpwZw'],
          category: 'No Ficción',
          tags: ['estrategia', 'filosofía', 'clásico', 'negocios'],
          attributes: {
            Autor: 'Sun Tzu',
            Editorial: 'Edaf',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 192,
          },
        },
        {
          title: 'Los Juegos del Hambre',
          description: 'Primera entrega de la trilogía distópica donde Katniss Everdeen debe luchar por su vida en los Juegos del Hambre.',
          price: 17.99,
          inStock: 70,
          slug: 'juegos-hambre',
          images: ['https://imgs.search.brave.com/83VFQFMHT7NpCUxT2MeGR-U6iMR_FybLiDqWA1MBDXg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzgyODgxNS1NTEE5/MzQwMDgwNzM0MF8w/OTIwMjUtVi53ZWJw'],
          category: 'Juvenil',
          tags: ['distopía', 'juvenil', 'aventura', 'bestseller'],
          attributes: {
            Autor: 'Suzanne Collins',
            Editorial: 'Molino',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 374,
          },
        },
        {
          title: 'Steve Jobs: La Biografía',
          description: 'Biografía autorizada del cofundador de Apple escrita por Walter Isaacson. La historia del visionario que cambió la tecnología.',
          price: 26.99,
          inStock: 35,
          slug: 'steve-jobs-biografia',
          images: ['https://imgs.search.brave.com/dwVCnIK2JIxycfsFcfI0Oab0Pm8_FU3ZYb1V9ZUstoY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzgxMDEyMi1NTEE4/MjY3OTg2NDEzNl8w/MzIwMjUtVi53ZWJw'],
          category: 'Biografías',
          tags: ['biografía', 'tecnología', 'apple', 'isaacson'],
          attributes: {
            Autor: 'Walter Isaacson',
            Editorial: 'Debate',
            Formato: 'Tapa dura',
            Idioma: 'Español',
            Páginas: 656,
          },
        },
        {
          title: 'El Poder del Ahora',
          description: 'Guía espiritual para encontrar la paz interior y vivir en el presente. Un bestseller de desarrollo personal.',
          price: 19.99,
          inStock: 65,
          slug: 'poder-ahora',
          images: ['https://imgs.search.brave.com/iaEa_y90DOe7K1YA4_QrChwMpYHrjM9hsO9Xc39kCxA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF85/MjMyNjEtTUxBMjY1/MTUwOTk0MjBfMTIy/MDE3LVYud2VicA'],
          category: 'Autoayuda',
          tags: ['autoayuda', 'espiritualidad', 'mindfulness', 'bestseller'],
          attributes: {
            Autor: 'Eckhart Tolle',
            Editorial: 'Grijalbo',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 240,
          },
        },
        {
          title: 'La Odisea',
          description: 'Epopeya griega de Homero que narra las aventuras de Odiseo en su regreso a Ítaca tras la guerra de Troya.',
          price: 15.99,
          inStock: 55,
          slug: 'odisea-homero',
          images: ['https://imgs.search.brave.com/YGZO9tnHdD9PW1D6KrTUyZSf-UHCu7Y1fU54HFODguo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29tYmVsZWRpdG9y/aWFsLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNS8xMC85/Nzg4NDk4MjUzMzUx/XzA0X2guanBn'],
          category: 'Ficción',
          tags: ['clásico', 'griego', 'épica', 'literatura antigua'],
          attributes: {
            Autor: 'Homero',
            Editorial: 'Alianza',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 448,
          },
        },
        {
          title: 'El Nombre del Viento',
          description: 'Primera parte de la Crónica del Asesino de Reyes. La historia de Kvothe, un joven prodigio que se convierte en leyenda.',
          price: 23.99,
          inStock: 50,
          slug: 'nombre-viento',
          images: ['https://imgs.search.brave.com/mxzHeICUa8BC8WWojbcWIIq3rUbfO-WIGJlrEOOUMls/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzgxNTU2Ni1NTEE4/MjE0NjcwMzg5Ml8w/MjIwMjUtVi53ZWJw'],
          category: 'Ficción',
          tags: ['fantasía', 'aventura', 'magia', 'bestseller'],
          attributes: {
            Autor: 'Patrick Rothfuss',
            Editorial: 'Plaza & Janés',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 880,
          },
        },
        {
          title: 'Sapiens: Una Historia Gráfica',
          description: 'Adaptación gráfica del bestseller de Harari. La historia de la humanidad contada a través de ilustraciones.',
          price: 28.99,
          inStock: 30,
          slug: 'sapiens-grafica',
          images: ['https://imgs.search.brave.com/Xl0fHMzF6dPzNIs9qyUFhbgiHdjYnUQCeytJyq3d9bU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/XzcyMzgwNi1NTEE1/MTE2ODY1ODM5OF8w/ODIwMjItVi53ZWJw'],
          category: 'No Ficción',
          tags: ['historia', 'cómic', 'ilustrado', 'educativo'],
          attributes: {
            Autor: 'Yuval Noah Harari',
            Editorial: 'Debate',
            Formato: 'Tapa dura',
            Idioma: 'Español',
            Páginas: 248,
          },
        },
        {
          title: 'El Alquimista',
          description: 'Fábula espiritual sobre un joven pastor que emprende un viaje en busca de un tesoro. Una historia sobre seguir tus sueños.',
          price: 16.99,
          inStock: 85,
          slug: 'alquimista',
          images: ['https://imgs.search.brave.com/KbF8xMr-vsrFB8DkE_0WOjGUlGw-aX2K00M2RJMJqjU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/Xzk2MTAzMS1DQlQ3/NjkzODIxMzMyOF8w/NjIwMjQtVi53ZWJw'],
          category: 'Ficción',
          tags: ['filosofía', 'espiritualidad', 'aventura', 'bestseller'],
          attributes: {
            Autor: 'Paulo Coelho',
            Editorial: 'Planeta',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 192,
          },
        },
        {
          title: 'Historia de España',
          description: 'Compendio completo de la historia de España desde la prehistoria hasta la actualidad. Obra de referencia académica.',
          price: 32.99,
          inStock: 25,
          slug: 'historia-espana',
          images: ['https://imgs.search.brave.com/4uu-fp9AQwKtB-HFp-1JvIs-EIQEXrN5TpX-tjsJptU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bWFyY2lhbHBvbnMu/ZXMvbWVkaWEvaW1n/L3BvcnRhZGFzLzIw/MTEvMTAvMjgvOTc4/ODQ5ODY3NjIwNC5q/cGc'],
          category: 'Historia',
          tags: ['historia', 'españa', 'académico', 'referencia'],
          attributes: {
            Autor: 'Varios Autores',
            Editorial: 'Crítica',
            Formato: 'Tapa dura',
            Idioma: 'Español',
            Páginas: 1200,
          },
        },
        {
          title: 'El Pequeño Príncipe (Edición Ilustrada)',
          description: 'Edición especial del clásico con ilustraciones originales del autor. Perfecta para coleccionistas y amantes de la literatura.',
          price: 19.99,
          inStock: 40,
          slug: 'principito-ilustrado',
          images: ['https://imgs.search.brave.com/1Bci2ePpB58etwMMVkZoNt1MX0BZa69qa1Q6neXHeD4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NDFrY2MwaGVEdUwu/anBn'],
          category: 'Infantil',
          tags: ['infantil', 'ilustrado', 'coleccionista', 'clásico'],
          attributes: {
            Autor: 'Antoine de Saint-Exupéry',
            Editorial: 'Emecé',
            Formato: 'Tapa dura',
            Idioma: 'Español',
            Páginas: 96,
          },
        },
        {
          title: 'El Secreto',
          description: 'Libro de autoayuda que explora la ley de la atracción y cómo nuestros pensamientos pueden cambiar nuestra realidad.',
          price: 18.99,
          inStock: 70,
          slug: 'secreto',
          images: ['https://imgs.search.brave.com/6z3QgiL-JuiSlEu5Uqd94e1w7TnFo1yW7vgKicST0UE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFUMGdSLU80eEwu/anBn'],
          category: 'Autoayuda',
          tags: ['autoayuda', 'ley atracción', 'desarrollo personal', 'bestseller'],
          attributes: {
            Autor: 'Rhonda Byrne',
            Editorial: 'Urano',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 224,
          },
        },
        {
          title: 'Crimen y Castigo',
          description: 'Obra maestra de Fiódor Dostoyevski sobre Raskólnikov, un estudiante que comete un asesinato y su lucha moral posterior.',
          price: 20.99,
          inStock: 45,
          slug: 'crimen-castigo',
          images: ['https://imgs.search.brave.com/Y19p_jvWGvpaYt8Q0Oh0OcrtAvAoVI5TapJNZMHIP1c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9RX05QXzJY/Xzk4NDU4OS1NTE00/NDM3MTk0NDc2NV8x/MjIwMjAtRS53ZWJw'],
          category: 'Ficción',
          tags: ['clásico', 'ruso', 'psicología', 'literatura universal'],
          attributes: {
            Autor: 'Fiódor Dostoyevski',
            Editorial: 'Alianza',
            Formato: 'Tapa blanda',
            Idioma: 'Español',
            Páginas: 672,
          },
        },
      ],
    },
  ],
};
